version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:274201610284:task-definition/process-pension-module:1"
        LoadBalancerInfo:
          ContainerName: "pensioncontainer"
          ContainerPort: "80"
        PlatformVersion: "LATEST"